apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-task-platform
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/vikashsharma0707/ai-task-platform-infra.git
    targetRevision: main
    path: k8s/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true